theme: jekyll-theme-hacker
title: LeanChess
description: A very small chess program
source: leanchess/leanchess

author:
  name: Dmitry Shechtman

social-network-links:
  rss: true
  email: "contact@leanchess.com"
  github: leanchess
  twitter: leanchess

share-links-active:
  twitter: true
  facebook: true
