theme: jekyll-theme-hacker
title: LeanChess
description: The world's smallest chess program
source: leanchess/leanchess

author:
  name: Dmitry Shechtman

social-network-links:
  rss: true
  email: "contact@leanchess.com"
  github: leanchess
  twitter: leanchess

share-links-active:
  twitter: true
  facebook: true

url-pretty: "leanchess.com"

github:
  repository_url: "https://github.com/leanchess/leanchess"
